### ISSUE TITLE
Folder icon looks odd when opened

### ISSUE THREAD

**Issue by saadq** [leo/material-ui#14]
When I open a folder that isn't the root directory of my project, the right border of the icon looks quite uneven as you can see here:

![screen shot 2016-08-24 at 3 43 42 pm](https://cloud.githubusercontent.com/assets/5678694/17950733/eb83dd4a-6a11-11e6-8c7b-1997f4ae9790.png)

It looks like it has to do with this code:

``` less
.tree-view .icon-repo:after, .tree-view .icon-file-directory:after {
    content: '';
    display: block;
    top: 9px;
    left: 4px;
    width: 13px;
    height: 8px;
    background: #263238;
    position: absolute;
    transition: transform 100ms;
    transform: scale(0);
}
```

If I change `left: 4px;` to `left: 3px;`, then it seems to fix the issue:

![screen shot 2016-08-24 at 3 44 09 pm](https://cloud.githubusercontent.com/assets/5678694/17950762/191c8694-6a12-11e6-99ac-2aaddf2d1dae.png)

Is this an issue or was this difference in the folder icon an intentional style choice? 

And I'm on a 15" MBP btw if that matters.
